def render() -> str:
    return '''"""Instruction-only runtime wrapper generated by Factory add_skill."""

from __future__ import annotations

from pathlib import Path


class ImportedSkillService:
    def ejecutar(self, context: dict) -> dict:
        skill_md = Path(__file__).resolve().parent / "SKILL.md"
        instructions = skill_md.read_text(encoding="utf-8", errors="replace")
        return {
            "ok": True,
            "type": "instruction_only",
            "message": "Skill de instrucciones cargado",
            "instructions": instructions,
            "received_context": context,
        }
'''
