def render(class_name: str, module_path: str) -> str:
    return f'''"""Runtime wrapper generated by Factory add_skill."""

from __future__ import annotations

from importlib import import_module
from pathlib import Path


MODULE_PATH = "{module_path}"


class {class_name}Service:
    def ejecutar(self, context: dict) -> dict:
        module = import_module(MODULE_PATH)

        if hasattr(module, "run"):
            result = module.run(context)
            if isinstance(result, dict):
                return result
            return {{"ok": False, "error": "run(context) no devolvio dict"}}

        if hasattr(module, "scan_skill"):
            target = context.get("path") or context.get("skill_path")
            if not target:
                return {{"ok": False, "error": "path es requerido"}}
            report = module.scan_skill(Path(target).resolve())
            if hasattr(report, "to_dict"):
                data = report.to_dict()
                data["ok"] = data.get("verdict") != "FAIL"
                return data
            return {{"ok": False, "error": "scan_skill no devolvio reporte compatible"}}

        return {{
            "ok": False,
            "error": "runtime generado no encontro run(context) ni scan_skill(path)",
        }}
'''
